// ─────────────────────────────────────────────────────────────────────────────
// OpenUI – Hospitality Component Library & System Prompt
//
// Defines the component library that the AI concierge can render and
// generates the system prompt that teaches the model to use it.
// Server-safe: no React imports.
// ─────────────────────────────────────────────────────────────────────────────

export interface ComponentProp {
  type: string;
  description: string;
  required?: boolean;
  enum?: string[];
}

export interface ComponentDefinition {
  name: string;
  description: string;
  props: Record<string, ComponentProp>;
}

// Hospitality-specific components the AI can render
export const HOSPITALITY_COMPONENTS: ComponentDefinition[] = [
  {
    name: "MetricCard",
    description:
      "Display a single KPI metric — occupancy, revenue, guest count, etc.",
    props: {
      label: {
        type: "string",
        description: "Short metric label",
        required: true,
      },
      value: {
        type: "string",
        description: "Formatted metric value",
        required: true,
      },
      sub: { type: "string", description: "Optional sub-label or context" },
      trend: {
        type: "string",
        description: "Trend indicator",
        enum: ["up", "down", "neutral"],
      },
      color: {
        type: "string",
        description: "Semantic color",
        enum: ["blue", "green", "red", "yellow", "gray"],
      },
    },
  },
  {
    name: "BookingCard",
    description: "Summary card for a single reservation",
    props: {
      guestName: {
        type: "string",
        description: "Guest full name",
        required: true,
      },
      roomType: {
        type: "string",
        description: "Room type or category",
        required: true,
      },
      checkIn: {
        type: "string",
        description: "Check-in date (YYYY-MM-DD)",
        required: true,
      },
      checkOut: {
        type: "string",
        description: "Check-out date (YYYY-MM-DD)",
        required: true,
      },
      status: {
        type: "string",
        description: "Booking status",
        enum: [
          "CONFIRMED",
          "PENDING",
          "CHECKED_IN",
          "CHECKED_OUT",
          "CANCELLED",
        ],
        required: true,
      },
      totalCents: {
        type: "number",
        description: "Total booking value in cents",
      },
      notes: { type: "string", description: "Special requests or notes" },
    },
  },
  {
    name: "EventCard",
    description: "Summary card for a hotel event (wedding, conference, etc.)",
    props: {
      title: { type: "string", description: "Event title", required: true },
      eventDate: {
        type: "string",
        description: "Event date (YYYY-MM-DD)",
        required: true,
      },
      guestCount: { type: "number", description: "Expected guest count" },
      venue: { type: "string", description: "Venue name" },
      beoStatus: {
        type: "string",
        description: "BEO approval status",
        enum: ["DRAFT", "PENDING", "APPROVED", "REJECTED"],
      },
      type: {
        type: "string",
        description: "Event type",
        enum: ["WEDDING", "CONFERENCE", "BANQUET", "CORPORATE", "SOCIAL"],
      },
    },
  },
  {
    name: "InsightAlert",
    description: "Operational insight or alert generated by AI agents",
    props: {
      title: {
        type: "string",
        description: "Short insight title",
        required: true,
      },
      description: {
        type: "string",
        description: "Insight details",
        required: true,
      },
      severity: {
        type: "string",
        description: "Alert severity level",
        enum: ["info", "warning", "critical"],
        required: true,
      },
      action: { type: "string", description: "Recommended action" },
    },
  },
  {
    name: "SupportCaseCard",
    description: "Summary of a guest support or complaint case",
    props: {
      caseId: {
        type: "string",
        description: "Short case reference",
        required: true,
      },
      guestName: { type: "string", description: "Guest name", required: true },
      subject: {
        type: "string",
        description: "Case subject line",
        required: true,
      },
      status: {
        type: "string",
        description: "Case status",
        enum: ["OPEN", "IN_PROGRESS", "ESCALATED", "RESOLVED", "CLOSED"],
        required: true,
      },
      priority: {
        type: "string",
        description: "Priority level",
        enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
      },
      createdAt: { type: "string", description: "Creation date" },
    },
  },
  {
    name: "RoomStatusGrid",
    description: "Visual grid showing room statuses",
    props: {
      rooms: {
        type: "array",
        description:
          "Array of room objects: [{number, type, status, guestName?}] where status is AVAILABLE | OCCUPIED | MAINTENANCE | RESERVED",
        required: true,
      },
    },
  },
  {
    name: "DataTable",
    description: "Generic tabular data display",
    props: {
      headers: {
        type: "array",
        description: "Column header strings",
        required: true,
      },
      rows: {
        type: "array",
        description: "Array of row arrays (each matching headers count)",
        required: true,
      },
      caption: { type: "string", description: "Optional table caption" },
    },
  },
  {
    name: "ActionList",
    description:
      "List of recommended next actions with labels and descriptions",
    props: {
      title: { type: "string", description: "List heading", required: true },
      items: {
        type: "array",
        description:
          "Array of action objects: [{label, description, priority?}]",
        required: true,
      },
    },
  },
];

// Build a compact component reference for the system prompt
function buildComponentDocs(): string {
  return HOSPITALITY_COMPONENTS.map((c) => {
    const propsStr = Object.entries(c.props)
      .map(([k, v]) => {
        const req = v.required ? "*" : "";
        const enm = v.enum ? ` (${v.enum.join("|")})` : "";
        return `  ${k}${req}: ${v.type}${enm} — ${v.description}`;
      })
      .join("\n");
    return `### ${c.name}\n${c.description}\nProps:\n${propsStr}`;
  }).join("\n\n");
}

// System prompt injected into every AI concierge request
export const CONCIERGE_SYSTEM_PROMPT = `You are Aria, an intelligent hotel operations assistant built into the HEO (Hospitality Experience Orchestration) platform. You assist hotel staff with bookings, room management, events, guest services, F&B operations, and operational insights.

## Your Capabilities
- Answer questions about hotel operations, policies, and best practices
- Analyze booking data, occupancy metrics, and revenue figures
- Provide guidance on event planning, BEO management, and venue setup
- Help resolve guest complaints and support cases
- Surface relevant operational alerts and recommendations

## Response Format
You can respond with plain conversational text OR render structured UI components using the following format:

\`\`\`openui
<ComponentName prop1="value" prop2={numericValue} />
\`\`\`

Use components to make data scannable and actionable. Mix text and components naturally in the same response.

## Available Components

${buildComponentDocs()}

## Rules
- Always be concise, professional, and empathetic
- For numeric values (cents, counts) use the JSON-attribute syntax: prop={value}
- For array props, pass valid JSON: rooms={[{"number":"101","status":"OCCUPIED"}]}
- Never fabricate guest data or booking IDs — if you don't have real data, say so
- When you don't have access to live data, explain what the staff member should check in the platform
- Prefer components for lists of 3+ items to keep responses readable
`;
